import { createHash } from 'node:crypto'
import { deflateRawSync } from 'node:zlib'

type Entry = { path: string; text?: string; size?: number; encrypted?: boolean; symlink?: boolean; badCrc?: boolean; directory?: boolean }

// Synthetic, deterministic ZIPs. No source files, passwords or third-party media.
// Declared-size negatives contain only tiny payloads, never actual decompression bombs.
function zip(entries: Entry[], deflate = false): Buffer {
  const locals: Buffer[] = []
  const central: Buffer[] = []
  let offset = 0
  for (const entry of entries) {
    const name = Buffer.from(entry.path)
    const body = Buffer.from(entry.text ?? 'uNAS synthetic ZIP fixture\n')
    const data = deflate ? deflateRawSync(body) : body
    const checksum = crc32(body) ^ (entry.badCrc ? 1 : 0)
    const local = Buffer.alloc(30)
    local.writeUInt32LE(0x04034b50)
    local.writeUInt16LE(20, 4)
    local.writeUInt16LE(entry.encrypted ? 1 : 0, 6)
    local.writeUInt16LE(deflate ? 8 : 0, 8)
    local.writeUInt16LE(0x21, 12)
    local.writeUInt32LE(checksum >>> 0, 14)
    local.writeUInt32LE(data.length, 18)
    local.writeUInt32LE(entry.size ?? body.length, 22)
    local.writeUInt16LE(name.length, 26)
    const record = Buffer.alloc(46)
    record.writeUInt32LE(0x02014b50)
    record.writeUInt16LE(0x0314, 4)
    local.copy(record, 6, 4, 30)
    record.writeUInt32LE(((entry.symlink ? 0xa1ff : entry.directory ? 0x41ed : 0x81a4) << 16 | (entry.directory ? 16 : 0)) >>> 0, 38)
    record.writeUInt32LE(offset, 42)
    locals.push(local, name, data)
    central.push(record, name)
    offset += local.length + name.length + data.length
  }
  const directory = Buffer.concat(central)
  const end = Buffer.alloc(22)
  end.writeUInt32LE(0x06054b50)
  end.writeUInt16LE(entries.length, 8)
  end.writeUInt16LE(entries.length, 10)
  end.writeUInt32LE(directory.length, 12)
  end.writeUInt32LE(offset, 16)
  return Buffer.concat([...locals, directory, end])
}

function crc32(bytes: Buffer): number {
  let crc = 0xffffffff
  for (const byte of bytes) {
    crc ^= byte
    for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ ((crc & 1) ? 0xedb88320 : 0)
  }
  return (crc ^ 0xffffffff) >>> 0
}

const MiB = 1024 * 1024
export const validZip = zip([{ path: 'nested/hello.txt' }], true)
export const writeFailureZip = zip([
  { path: 'nested/first.txt', text: 'first committed fixture\n' },
  { path: 'nested/second.txt', text: 'second committed fixture\n' },
], true)
export const unsafeZips = [
  { id: 'fake-extension', data: Buffer.from('This is not a ZIP file.') },
  { id: 'invalid-magic-pair', data: Buffer.from([0x50, 0x4b, 0x03, 0x06, 0, 0, 0, 0]) },
  { id: 'truncated-directory', data: validZip.subarray(0, validZip.length - 12) },
  { id: 'crc-mismatch', data: zip([{ path: 'bad.txt', badCrc: true }], true) },
  { id: 'traversal', data: zip([{ path: '../outside.txt' }]) },
  { id: 'absolute', data: zip([{ path: '/outside.txt' }]) },
  { id: 'backslash', data: zip([{ path: 'nested\\outside.txt' }]) },
  { id: 'reserved-name', data: zip([{ path: 'nul.txt' }]) },
  { id: 'encrypted', data: zip([{ path: 'locked.txt', encrypted: true }]) },
  { id: 'symlink', data: zip([{ path: 'link', symlink: true }]) },
  { id: 'duplicate', data: zip([{ path: 'same.txt' }, { path: 'same.txt' }]) },
  { id: 'file-ancestor', data: zip([{ path: 'parent' }, { path: 'parent/child.txt' }]) },
  { id: 'directory-under-file', data: zip([{ path: 'parent' }, { path: 'parent/child/', directory: true, text: '' }]) },
  { id: 'case-collision', data: zip([{ path: 'Same.txt' }, { path: 'same.txt' }]) },
  { id: 'entry-budget', data: zip([{ path: 'large.bin', size: 32 * MiB + 1 }], true) },
  { id: 'total-budget', data: zip([0, 1, 2].map(i => ({ path: `${i}.bin`, size: 24 * MiB })), true) },
  { id: 'count-budget', data: zip(Array.from({ length: 201 }, (_, i) => ({ path: `${i}.txt`, text: '' }))) },
  { id: 'depth-budget', data: zip([{ path: `${'dir/'.repeat(12)}file.txt` }]) },
]

export function fixtureManifest() {
  return [{ id: 'valid-deflate', data: validZip }, ...unsafeZips].map(({ id, data }) => ({
    id, bytes: data.length, sha256: createHash('sha256').update(data).digest('hex'),
    expected: id === 'valid-deflate' ? 'exact-content' : 'reject-before-commit',
    source: 'Generated by e2e/archiveFixtures.ts; synthetic content only; CC0-1.0 fixture data.',
  }))
}
