import { test, expect } from './fixtures'
import { validZip, writeFailureZip } from './archiveFixtures'

const probe = 'unas-sp04-write-failure-fixtures'

async function installDirectory(page: import('@playwright/test').Page) {
  await page.evaluate(async ({ name, base64 }) => {
    const directory = await (await navigator.storage.getDirectory()).getDirectoryHandle(name, { create: true })
    const writable = await (await directory.getFileHandle('input.zip', { create: true })).createWritable()
    await writable.write(Uint8Array.from(atob(base64), byte => byte.charCodeAt(0)))
    await writable.close()
    Object.defineProperty(globalThis, 'showDirectoryPicker', { configurable: true, value: async () => directory })
  }, { name: probe, base64: writeFailureZip.toString('base64') })
}

async function openWritableFileManager(page: import('@playwright/test').Page) {
  await page.locator('.app-icon--file-manager').click()
  const app = page.locator('[data-app-id="file-manager"]')
  await app.getByRole('button', { name: '选择本地目录并打开系统目录选择器', exact: true }).click()
  await app.getByRole('button', { name: '只读模式，点击开启写入模式' }).click()
  await app.getByRole('button', { name: '继续并授权' }).click()
  return app
}

async function injectWriteFailure(page: import('@playwright/test').Page) {
  await page.evaluate(async () => {
    const root = await navigator.storage.getDirectory()
    const probeDirectory = await root.getDirectoryHandle('unas-sp04-write-failure-fixtures')
    const file = await probeDirectory.getFileHandle('input.zip')
    const filePrototype = Object.getPrototypeOf(file) as { createWritable: (options?: unknown) => Promise<unknown> }
    const nativeCreateWritable = filePrototype.createWritable
    Object.defineProperty(globalThis, '__unasNativeCreateWritable', { configurable: true, value: nativeCreateWritable })
    Object.defineProperty(filePrototype, 'createWritable', {
      configurable: true,
      value: async function (this: FileSystemFileHandle, options?: unknown) {
        if (this.name === 'second.txt') {
          return {
            async write() { throw new DOMException('Synthetic write failure for SP-04-C.', 'NotAllowedError') },
            async close() { return undefined },
            async abort() { return undefined },
          }
        }
        return await nativeCreateWritable.call(this, options)
      },
    })
  })
}

async function restoreWriteAccess(page: import('@playwright/test').Page) {
  await page.evaluate(async () => {
    const root = await navigator.storage.getDirectory()
    const probeDirectory = await root.getDirectoryHandle('unas-sp04-write-failure-fixtures')
    const file = await probeDirectory.getFileHandle('input.zip')
    const filePrototype = Object.getPrototypeOf(file) as { createWritable: (options?: unknown) => Promise<unknown> }
    const nativeCreateWritable = (globalThis as typeof globalThis & { __unasNativeCreateWritable?: typeof filePrototype.createWritable }).__unasNativeCreateWritable
    if (nativeCreateWritable) Object.defineProperty(filePrototype, 'createWritable', { configurable: true, value: nativeCreateWritable })
  })
}

async function directChildNames(page: import('@playwright/test').Page) {
  return await page.evaluate(async name => {
    const directory = await (await navigator.storage.getDirectory()).getDirectoryHandle(name)
    const names: string[] = []
    for await (const key of directory.keys()) names.push(key)
    return names.sort()
  }, probe)
}

test('ZIP commit failure reports partial output and recovers on a later attempt', async ({ extension }, testInfo) => {
  test.setTimeout(120_000)
  await testInfo.attach('fixture-manifest', {
    body: JSON.stringify({
      id: 'write-failure-two-file',
      bytes: writeFailureZip.length,
      expected: 'failed-commit-with-partial-output',
      source: 'Generated by e2e/archiveFixtures.ts; synthetic content only; CC0-1.0 fixture data.',
    }, null, 2),
    contentType: 'application/json',
  })
  const page = await extension.context.newPage()
  await page.goto(`chrome-extension://${extension.extensionId}/newtab.html`)
  await installDirectory(page)
  const app = await openWritableFileManager(page)
  await expect(app.getByRole('button', { name: '解压 input.zip' })).toBeEnabled()

  try {
    await injectWriteFailure(page)
    page.once('dialog', dialog => dialog.accept())
    await app.getByRole('button', { name: '解压 input.zip' }).click()
    await expect(app.getByRole('alert')).toContainText('解压结果写入失败；“input（解压）”可能包含 1 个已写入文件，未将任务标记为成功。')
    expect(await directChildNames(page)).toEqual(['input.zip', 'input（解压）'])
    const partialContent = await page.evaluate(async name => {
      const root = await navigator.storage.getDirectory()
      const directory = await root.getDirectoryHandle(name)
      const output = await directory.getDirectoryHandle('input（解压）')
      const nested = await output.getDirectoryHandle('nested')
      return (await nested.getFileHandle('first.txt')).getFile().then(file => file.text())
    }, probe)
    expect(partialContent).toBe('first committed fixture\n')

    await restoreWriteAccess(page)
    page.once('dialog', dialog => dialog.accept())
    await app.getByRole('button', { name: '解压 input.zip' }).click()
    await expect(app.getByRole('status')).toContainText('已解压 2 个文件到“input（解压 2）”。')
    expect(await directChildNames(page)).toEqual(['input.zip', 'input（解压 2）', 'input（解压）'])
    expect(extension.errors).toEqual([])
    expect(extension.remoteRequests).toEqual([])
  } finally {
    await page.evaluate(async name => {
      await (await navigator.storage.getDirectory()).removeEntry(name, { recursive: true })
    }, probe)
  }
})
