import { test, expect, workspace, openApp, closeApp, revealRuntimePanel } from './fixtures'

test('New Tab override launches and reuses one Workspace; invalid messages are rejected', async ({ extension }) => {
  const page = await extension.context.newPage()
  await page.goto('chrome://newtab/')
  await expect(page.getByRole('navigation', { name: '应用快捷方式' })).toBeVisible()
  await page.locator('.app-icon--fetcher').click()
  await expect.poll(() => extension.context.pages().filter((tab) => tab.url().includes('/workspace.html')).length).toBe(1)
  const owner = extension.context.pages().find((tab) => tab.url().includes('/workspace.html'))!
  const fetcherWindow = owner.locator('[data-app-id="fetcher"]')
  await expect(fetcherWindow).toBeVisible()
  await expect(fetcherWindow).toHaveCSS('outline-style', 'none')
  await expect(owner.locator('.rp-edge-trigger')).toBeEmpty()
  const second = await extension.context.newPage()
  await second.goto(`chrome-extension://${extension.extensionId}/newtab.html`)
  await second.locator('.app-icon--file-manager').click()
  await expect(owner.locator('[data-app-id="file-manager"]')).toBeVisible()
  await expect(second.locator('.app-icon--ps, .app-icon--transcode, .app-icon--pdf, .app-icon--image, .app-icon--archive, .app-icon--tasks')).toHaveCount(0)
  expect(extension.context.pages().filter((tab) => tab.url().includes('/workspace.html'))).toHaveLength(1)
  const responses = await second.evaluate(async () => {
    const runtime = (globalThis as unknown as { chrome: { runtime: { sendMessage: (message: unknown) => Promise<{ ok: boolean }> } } }).chrome.runtime
    return Promise.all([
      { schemaVersion: 2, action: 'workspace.launch', appId: 'fetcher' },
      { schemaVersion: 1, action: 'workspace.launch', appId: 'javascript:alert(1)' },
      { schemaVersion: 1, action: 'workspace.launch', appId: 'fetcher', url: 'https://example.com' },
    ].map((message) => runtime.sendMessage(message)))
  })
  expect(responses.every((response) => response.ok === false)).toBe(true)
  expect(extension.context.pages().filter((tab) => tab.url().includes('/workspace.html'))).toHaveLength(1)
  const duplicate = await extension.context.newPage()
  await duplicate.goto(`chrome-extension://${extension.extensionId}/workspace.html#fetcher`)
  await expect(duplicate.getByRole('heading', { name: 'Workspace 已在另一标签页运行' })).toBeVisible()
  await expect(duplicate.locator('[data-app-id="fetcher"]')).toHaveCount(0)
  await duplicate.close()
  expect(extension.remoteRequests).toEqual([])
  expect(extension.errors).toEqual([])
})

test('partial failure keeps successful fixture and exposes the failed item', async ({ extension }) => {
  const page = await workspace(extension, 'file-manager')
  const app = page.locator('[data-app-id="file-manager"]')
  await expect(app.locator('.fm-address')).toHaveText('/Workspace')
  await revealRuntimePanel(page)
  await page.getByRole('combobox', { name: '模拟场景' }).selectOption('partial-failure')
  await openApp(page, 'file-manager')
  await app.getByRole('button', { name: '模拟选择文件', exact: true }).click()
  await expect(app.getByRole('status')).toContainText('成功 1 项，失败 1 项')
  await expect(app.getByRole('status')).toContainText('sample-document')
  await expect(app.getByRole('button', { name: 'sample-image.png，模拟文件', exact: true })).toBeVisible()
  await expect(app.getByRole('button', { name: 'sample-document.pdf，模拟文件', exact: true })).toHaveCount(0)
  expect(await page.locator('input[type="file"]').count()).toBe(0)
  expect(extension.errors).toEqual([])
})

test('fixture intake, mock result inspection and trash restoration never select real files', async ({ extension }) => {
  const page = await workspace(extension, 'file-manager')
  const app = page.locator('[data-app-id="file-manager"]')
  await expect(app.locator('.fm-address')).toHaveText('/Workspace')
  expect(await page.locator('input[type="file"]').count()).toBe(0)
  let downloads = 0
  page.on('download', () => { downloads += 1 })
  await app.getByRole('button', { name: '模拟选择文件', exact: true }).click()
  const fixture = app.getByRole('button', { name: 'sample-image.png，模拟文件', exact: true })
  await expect(fixture).toBeVisible()
  await fixture.click()
  await app.getByRole('button', { name: '查看模拟结果', exact: true }).click()
  await expect(app.getByRole('status')).toContainText('未生成可下载文件')
  page.once('dialog', (dialog) => dialog.accept())
  await app.getByRole('button', { name: '移入回收站', exact: true }).click()
  await expect(fixture).toHaveCount(0)
  await app.getByRole('button', { name: '回收站', exact: true }).click()
  await expect(fixture).toBeVisible()
  await fixture.click()
  await app.getByRole('button', { name: '恢复', exact: true }).click()
  await expect(fixture).toHaveCount(0)
  await app.getByRole('button', { name: '我的文件', exact: true }).click()
  await expect(fixture).toBeVisible()
  expect(downloads).toBe(0)
  expect(extension.errors).toEqual([])
})

test('download cancellation persists after reopening the App', async ({ extension }) => {
  const page = await workspace(extension, 'fetcher')
  const downloader = page.locator('[data-app-id="fetcher"]')
  await downloader.getByRole('button', { name: '添加任务', exact: true }).click()
  await downloader.getByLabel(/^(模拟来源链接|下载链接)$/).fill('https://example.com/mock-video\nhttps://example.org/mock-video')
  await downloader.getByRole('button', { name: /^(添加模拟任务|确认添加)$/ }).click()
  const row = downloader.locator('.dl-row').filter({ hasText: 'example.com' })
  await expect(row).toBeVisible()
  await row.click()
  await downloader.getByRole('button', { name: 'stop-selected-downloads' }).click()
  await expect(row).toContainText(/取消/)
  const secondRow = downloader.locator('.dl-row').filter({ hasText: 'example.org' })
  await secondRow.click()
  await downloader.getByRole('button', { name: 'stop-selected-downloads' }).click()
  await expect(secondRow).toContainText(/取消/)
  await closeApp(page, 'fetcher')
  const reopened = await openApp(page, 'fetcher')
  await expect(reopened.locator('.dl-row').filter({ hasText: 'example.org' })).toContainText(/取消/)
  expect(extension.remoteRequests).toEqual([])
  expect(extension.errors).toEqual([])
})
