import { test, expect, workspace, openApp, closeApp, revealRuntimePanel } from './fixtures'

test('New Tab opens every built-in App locally and rejects legacy cross-tab launches', async ({ extension }) => {
  const page = await extension.context.newPage()
  await page.goto('chrome://newtab/')
  await expect(page.getByRole('navigation', { name: '应用快捷方式' })).toBeVisible()
  const tabCount = extension.context.pages().length
  await page.locator('.app-icon--browser').click()
  await page.getByLabel('名称', { exact: true }).fill('保留当前标签页草稿')
  await page.locator('.app-icon--fetcher').click()
  const fetcherWindow = page.locator('[data-app-id="fetcher"]')
  await expect(fetcherWindow).toBeVisible()
  await expect(fetcherWindow).toHaveCSS('outline-style', 'none')
  await expect(page.locator('.rp-edge-trigger')).toBeEmpty()
  await page.locator('.app-icon--file-manager').click()
  await expect(page.locator('[data-app-id="file-manager"]')).toBeVisible()
  await expect(page.getByRole('heading', { name: '打开本地目录' })).toBeVisible()
  await expect(page.getByLabel('名称', { exact: true })).toHaveValue('保留当前标签页草稿')
  expect(extension.context.pages()).toHaveLength(tabCount)
  const second = await extension.context.newPage()
  await second.goto(`chrome-extension://${extension.extensionId}/newtab.html`)
  await second.locator('.app-icon--file-manager').click()
  await expect(second.locator('[data-app-id="file-manager"]')).toBeVisible()
  await expect(second.getByRole('heading', { name: '打开本地目录' })).toBeVisible()
  await expect(second.locator('.app-icon--ps, .app-icon--transcode, .app-icon--pdf, .app-icon--image, .app-icon--archive, .app-icon--tasks')).toHaveCount(0)
  expect(extension.context.pages().filter((tab) => tab.url().includes('/workspace.html'))).toHaveLength(0)
  const responses = await second.evaluate(async () => {
    const runtime = (globalThis as unknown as { browser: { runtime: { sendMessage: (message: unknown) => Promise<{ ok: boolean }> } } }).browser.runtime
    return Promise.all([
      { schemaVersion: 1, action: 'workspace.launch', appId: 'fetcher' },
      { schemaVersion: 2, action: 'workspace.launch', appId: 'fetcher' },
      { schemaVersion: 1, action: 'workspace.launch', appId: 'javascript:alert(1)' },
      { schemaVersion: 1, action: 'workspace.launch', appId: 'fetcher', url: 'https://example.com' },
    ].map((message) => runtime.sendMessage(message)))
  })
  expect(responses.every((response) => response.ok === false)).toBe(true)
  expect(extension.context.pages().filter((tab) => tab.url().includes('/workspace.html'))).toHaveLength(0)
  const duplicate = await extension.context.newPage()
  await duplicate.goto(`chrome-extension://${extension.extensionId}/workspace.html#fetcher`)
  await expect(duplicate.locator('[data-app-id="fetcher"]')).toBeVisible()
  await expect(duplicate.locator('.dl-row')).toContainText('模拟产品发布会回放')
  await duplicate.close()
  expect(extension.remoteRequests).toEqual([])
  expect(extension.errors).toEqual([])
})

test('Files keeps an explicit directory-authorization boundary and never mounts a file input', async ({ extension }) => {
  const page = await workspace(extension, 'file-manager')
  const app = page.locator('[data-app-id="file-manager"]')
  await expect(app.getByRole('heading', { name: '打开本地目录' })).toBeVisible()
  await expect(app.getByRole('button', { name: '选择本地目录并打开系统目录选择器', exact: true })).toBeVisible()
  await expect(page.locator('input[type="file"]')).toHaveCount(0)
  await expect(app).toContainText('仅读取目录；需要写入时再确认。')
  expect(extension.errors).toEqual([])
})

test('download cancellation persists after reopening the App', async ({ extension }) => {
  const page = await workspace(extension, 'fetcher')
  const downloader = page.locator('[data-app-id="fetcher"]')
  const status = downloader.locator('.dl-status')
  const tableHeader = downloader.locator('.dl-head')
  await expect(status).toHaveCSS('background-color', 'rgb(32, 34, 37)')
  await expect(tableHeader).toHaveCSS('background-color', 'rgb(32, 34, 37)')
  await page.evaluate(() => document.documentElement.setAttribute('data-theme', 'light'))
  await expect(status).toHaveCSS('background-color', 'rgb(248, 249, 250)')
  await expect(tableHeader).toHaveCSS('background-color', 'rgb(248, 249, 250)')
  await page.evaluate(() => document.documentElement.removeAttribute('data-theme'))
  await downloader.getByRole('button', { name: '添加任务', exact: true }).click()
  await expect(downloader).toContainText('浏览器默认下载位置')
  await expect(downloader).not.toContainText('选择模拟目录')
  await downloader.getByLabel(/^(模拟来源链接|下载链接)$/).fill('https://example.com/mock-video\nhttps://example.org/mock-video')
  await downloader.getByRole('button', { name: /^(添加模拟任务|确认添加)$/ }).click()
  const row = downloader.locator('.dl-row').filter({ hasText: 'example.com' })
  await expect(row).toBeVisible()
  await row.click()
  await downloader.getByRole('button', { name: 'stop-selected-downloads' }).click()
  await expect(row).toContainText(/取消/)
  const secondRow = downloader.locator('.dl-row').filter({ hasText: 'example.org' })
  await secondRow.click()
  await downloader.getByRole('button', { name: 'stop-selected-downloads' }).click()
  await expect(secondRow).toContainText(/取消/)
  await closeApp(page, 'fetcher')
  const reopened = await openApp(page, 'fetcher')
  await expect(reopened.locator('.dl-row').filter({ hasText: 'example.org' })).toContainText(/取消/)
  expect(extension.remoteRequests).toEqual([])
  expect(extension.errors).toEqual([])
})
