import { test, expect, revealRuntimePanel } from './fixtures'

test('two local desktops share submissions, cancellation and file mutations', async ({ extension }, testInfo) => {
  const owner = await extension.context.newPage()
  const url = `chrome-extension://${extension.extensionId}/newtab.html`
  await owner.goto(url)
  await owner.locator('.app-icon--fetcher').click()
  await expect(owner.locator('.dl-row')).toContainText('模拟产品发布会回放')
  const client = await extension.context.newPage()
  await client.goto(url)
  const count = extension.context.pages().length
  await client.locator('.app-icon--fetcher').click()
  const app = client.locator('[data-app-id="fetcher"]')
  await app.getByRole('button', { name: '添加任务', exact: true }).click()
  await app.getByLabel('模拟来源链接').fill('https://example.com/shared')
  await app.getByRole('button', { name: '添加模拟任务', exact: true }).click()
  const row = app.locator('.dl-row').filter({ hasText: 'example.com' })
  await expect(row).toContainText('12.0%')
  await expect(owner.locator('.dl-row').filter({ hasText: 'example.com' })).toContainText('12.0%')
  await row.click()
  await app.getByRole('button', { name: 'stop-selected-downloads' }).click()
  await expect(row).toContainText('取消')
  await expect(owner.locator('.dl-row').filter({ hasText: 'example.com' })).toContainText('取消')
  await client.locator('.app-icon--file-manager').click()
  const files = client.locator('[data-app-id="file-manager"]')
  await expect(files.getByRole('heading', { name: '选择本地目录' })).toBeVisible()
  await expect(files).toContainText('仅访问你选择的目录，不上传文件')
  expect(extension.context.pages()).toHaveLength(count)
  await client.screenshot({ path: testInfo.outputPath('same-tab-workspace-client.png') })
  await client.locator('.app-icon--fetcher').click()
  await app.getByRole('button', { name: '添加任务', exact: true }).click()
  await app.getByLabel('模拟来源链接').fill('https://example.org/client-close')
  await app.getByRole('button', { name: '添加模拟任务', exact: true }).click()
  await expect(app.locator('.dl-row').filter({ hasText: 'example.org' })).toContainText('12.0%')
  // Closing a client neither stops nor replaces the owner.
  await client.close({ runBeforeUnload: true })
  await expect.poll(() => client.isClosed()).toBe(true)
  await expect(owner.locator('.dl-row').filter({ hasText: 'example.org' })).toContainText('12.0%')
  await revealRuntimePanel(owner)
  await expect(owner.getByRole('combobox', { name: '模拟场景' })).toBeVisible()
  expect(extension.errors).toEqual([])
  expect(extension.remoteRequests).toEqual([])
})

test('owner loss disables client tools without creating tabs or replaying work', async ({ extension }) => {
  const url = `chrome-extension://${extension.extensionId}/newtab.html`
  const owner = await extension.context.newPage()
  await owner.goto(url)
  await owner.locator('.app-icon--fetcher').click()
  await expect(owner.locator('.dl-row')).toBeVisible()
  const client = await extension.context.newPage()
  await client.goto(url)
  await client.locator('.app-icon--fetcher').click()
  await expect(client.locator('.dl-row')).toBeVisible()
  const clientApp = client.locator('[data-app-id="fetcher"]')
  await clientApp.getByRole('button', { name: '添加任务', exact: true }).click()
  await clientApp.getByLabel('模拟来源链接').fill('https://example.com/owner-close')
  await clientApp.getByRole('button', { name: '添加模拟任务', exact: true }).click()
  const pendingRow = clientApp.locator('.dl-row').filter({ hasText: 'example.com' })
  await expect(pendingRow).toContainText('12.0%')
  const count = extension.context.pages().length
  await owner.close({ runBeforeUnload: true })
  await expect.poll(() => owner.isClosed()).toBe(true)
  await expect(clientApp.getByRole('alert')).toContainText('连接已中断')
  await expect(pendingRow).toHaveCount(0)
  await expect(clientApp).not.toContainText('成功')
  expect(extension.context.pages()).toHaveLength(count - 1)
  expect(extension.errors).toEqual([])
})
