import { test, expect } from './fixtures'

test('Link App validates HTTPS and persists create, edit and delete across reloads', async ({ extension }) => {
  const page = await extension.context.newPage()
  await page.goto(`chrome-extension://${extension.extensionId}/newtab.html`)
  await page.locator('.app-icon--browser').click()
  const app = page.locator('[data-app-id="browser"]')
  await app.getByLabel('名称', { exact: true }).fill('Example')
  await app.getByLabel('HTTPS 网址', { exact: true }).fill('javascript:alert(1)')
  await app.getByRole('button', { name: '添加网址 App' }).click()
  await expect(app.getByRole('alert')).toContainText('只允许完整的 HTTPS')
  await app.getByLabel('HTTPS 网址', { exact: true }).fill('https://example.com/path')
  await app.getByRole('button', { name: '添加网址 App' }).click()
  await page.reload()
  await page.locator('.app-icon--browser').click()
  await expect(app.locator('li')).toContainText('https://example.com/path')
  await app.getByRole('button', { name: '编辑 Example', exact: true }).click()
  await app.getByLabel('名称', { exact: true }).fill('Changed')
  await app.getByLabel('HTTPS 网址', { exact: true }).fill('https://example.org/updated')
  await app.getByRole('button', { name: '保存修改' }).click()
  await expect(app.locator('li')).toContainText('https://example.org/updated')
  await app.getByRole('button', { name: '删除 Changed', exact: true }).click()
  await page.reload()
  await page.locator('.app-icon--browser').click()
  await expect(app).toContainText('尚未添加网址 App')
  await page.evaluate(() => localStorage.setItem('unas-link-apps-v1', JSON.stringify([
    { schemaVersion: 1, id: 'duplicate', name: 'One', url: 'https://example.com/', icon: 'globe' },
    { schemaVersion: 1, id: 'duplicate', name: 'Two', url: 'https://example.org/', icon: 'bookmark' },
  ])))
  await page.reload()
  await page.locator('.app-icon--browser').click()
  await expect(app.getByRole('alert')).toContainText('重复项目')
  expect(extension.errors).toEqual([])
  expect(extension.remoteRequests).toEqual([])
})
