import { test, expect, workspace, openApp } from './fixtures'

test('Workspace close publishes interruption, releases ownership and refresh resets fixtures', async ({ extension }) => {
  const owner = await workspace(extension, 'image')
  const newtab = await extension.context.newPage()
  await newtab.goto(`chrome-extension://${extension.extensionId}/newtab.html`)
  const summary = newtab.getByRole('complementary', { name: 'Workspace 任务摘要' })
  const app = owner.locator('[data-app-id="image"]')
  await app.getByRole('button', { name: '模拟选择固定 fixture' }).click()
  await app.getByRole('button', { name: '创建模拟任务' }).click()
  await expect(summary).toContainText('demo-job-001')
  const duplicate = await extension.context.newPage()
  await duplicate.goto(`chrome-extension://${extension.extensionId}/workspace.html#tasks`)
  await expect(duplicate.getByRole('heading', { name: 'Workspace 已在另一标签页运行' })).toBeVisible()
  owner.on('dialog', dialog => dialog.accept())
  await owner.close({ runBeforeUnload: true })
  await expect(summary).toContainText('Workspace 已关闭')
  await expect(summary).toContainText('failed')
  await duplicate.getByRole('button', { name: '重新确认所有权' }).click()
  await expect(duplicate.locator('[data-app-id="tasks"]')).toBeVisible()
  await expect(summary).not.toContainText('demo-job-001')
  const freshApp = await openApp(duplicate, 'image')
  await freshApp.getByRole('button', { name: '模拟选择固定 fixture' }).click()
  await freshApp.getByRole('button', { name: '创建模拟任务' }).click()
  await expect(summary).toContainText('demo-job-001')
  duplicate.on('dialog', dialog => dialog.accept())
  await duplicate.reload()
  await expect(duplicate.locator('[data-app-id="image"]')).toBeVisible()
  await expect(summary).not.toContainText('demo-job-001')
  await expect(duplicate.locator('[data-app-id="image"]')).toContainText('尚无当前任务')
  expect(extension.errors).toEqual([])
  expect(extension.remoteRequests).toEqual([])
})

test('Link App validates HTTPS and persists create, edit and delete across reloads', async ({ extension }) => {
  const page = await extension.context.newPage()
  await page.goto(`chrome-extension://${extension.extensionId}/newtab.html`)
  await page.locator('.app-icon--browser').click()
  const app = page.locator('[data-app-id="browser"]')
  await app.getByLabel('名称', { exact: true }).fill('Example')
  await app.getByLabel('HTTPS 网址', { exact: true }).fill('javascript:alert(1)')
  await app.getByRole('button', { name: '添加网址 App' }).click()
  await expect(app.getByRole('alert')).toContainText('只允许完整的 HTTPS')
  await app.getByLabel('HTTPS 网址', { exact: true }).fill('https://example.com/path')
  await app.getByRole('button', { name: '添加网址 App' }).click()
  await page.reload()
  await page.locator('.app-icon--browser').click()
  await expect(app.locator('li')).toContainText('https://example.com/path')
  await app.getByRole('button', { name: '编辑 Example', exact: true }).click()
  await app.getByLabel('名称', { exact: true }).fill('Changed')
  await app.getByLabel('HTTPS 网址', { exact: true }).fill('https://example.org/updated')
  await app.getByRole('button', { name: '保存修改' }).click()
  await expect(app.locator('li')).toContainText('https://example.org/updated')
  await app.getByRole('button', { name: '删除 Changed', exact: true }).click()
  await page.reload()
  await page.locator('.app-icon--browser').click()
  await expect(app).toContainText('尚未添加网址 App')
  await page.evaluate(() => localStorage.setItem('unas-link-apps-v1', JSON.stringify([
    { schemaVersion: 1, id: 'duplicate', name: 'One', url: 'https://example.com/', icon: 'globe' },
    { schemaVersion: 1, id: 'duplicate', name: 'Two', url: 'https://example.org/', icon: 'bookmark' },
  ])))
  await page.reload()
  await page.locator('.app-icon--browser').click()
  await expect(app.getByRole('alert')).toContainText('重复项目')
  expect(extension.errors).toEqual([])
  expect(extension.remoteRequests).toEqual([])
})
