import { test, expect, workspace } from './fixtures'
import { checkWindowDraftAndFocus } from './windowChecks'

test('minimized Apps retain drafts and focus follows the visible window', async ({ extension }) => {
  const page = await extension.context.newPage()
  await page.goto(`chrome-extension://${extension.extensionId}/newtab.html`)
  await checkWindowDraftAndFocus(page)
  expect(extension.errors).toEqual([])
})

test('New Tab reads owner updates and external cancellation refreshes the download list', async ({ extension }, testInfo) => {
  const tab = await extension.context.newPage()
  await tab.goto(`chrome-extension://${extension.extensionId}/newtab.html`)
  await tab.locator('.rp-edge-trigger').click()
  const summary = tab.getByRole('region', { name: 'Workspace 任务摘要' })
  await expect(summary).toContainText('暂无模拟任务')
  await expect(tab.getByRole('button', { name: '停止', exact: true })).toHaveCount(0)
  await expect(tab.getByRole('button', { name: '推进模拟步骤' })).toHaveCount(0)
  const owner = await workspace(extension, 'fetcher')
  await owner.locator('.rp-edge-trigger').click()
  const app = owner.locator('[data-app-id="fetcher"]')
  const row = app.locator('.dl-row').first()
  await expect(summary.locator('[data-job-id="demo-download-001"]')).toContainText('运行中')
  await owner.locator('.rp-task-group').first().click()
  await owner.getByRole('button', { name: '停止', exact: true }).click()
  await expect(row).toContainText('取消')
  await expect(app.getByRole('button', { name: 'stop-selected-downloads' })).toBeDisabled()
  await expect(summary.locator('[data-job-id="demo-download-001"]')).toContainText('已取消')

  await app.getByRole('button', { name: '添加任务', exact: true }).click()
  await app.getByLabel('模拟来源链接').fill('https://example.com/synchronized')
  await app.getByRole('button', { name: '添加模拟任务', exact: true }).click()
  const created = app.locator('.dl-row').filter({ hasText: 'example.com' })
  await expect(created).toContainText('12.0%')
  await owner.getByRole('button', { name: '推进模拟步骤' }).click()
  await expect(created).toContainText('68.0%')
  await owner.getByRole('button', { name: '推进模拟步骤' }).click()
  await expect(created).toContainText('100.0%')
  await expect(app.getByRole('button', { name: 'stop-selected-downloads' })).toBeDisabled()
  await expect(summary.locator('li').filter({ hasText: 'example.com' })).toContainText('模拟完成')
  await tab.bringToFront()
  await tab.screenshot({ path: testInfo.outputPath('newtab-owner-summary.png') })
  const tabCount = extension.context.pages().length
  await summary.getByRole('button', { name: '在当前页面管理任务' }).click()
  await expect(tab.locator('[data-app-id="fetcher"]')).toBeVisible()
  await expect(tab.locator('.dl-row').filter({ hasText: 'example.com' })).toContainText('100.0%')
  expect(extension.context.pages()).toHaveLength(tabCount)
  expect(extension.context.pages().filter((page) => page.url().includes('/workspace.html'))).toHaveLength(1)
  expect(extension.errors).toEqual([])
  expect(extension.remoteRequests).toEqual([])
})
