import { test, expect } from './fixtures'
import { checkWindowDraftAndFocus } from './windowChecks'

test('minimized Apps retain drafts and focus follows the visible window', async ({ extension }) => {
  const page = await extension.context.newPage()
  await page.goto(`chrome-extension://${extension.extensionId}/newtab.html`)
  await checkWindowDraftAndFocus(page)
  expect(extension.errors).toEqual([])
})

test('runtime panel shows resource status and omits GPU capability details and simulated task summary', async ({ extension }) => {
  const tab = await extension.context.newPage()
  await tab.goto(`chrome-extension://${extension.extensionId}/newtab.html`)
  await tab.locator('.rp-edge-trigger').hover()
  await expect(tab.getByRole('button', { name: '展开系统详情' })).toBeVisible()
  await expect(tab.locator('.rp-system-details')).toHaveCount(0)
  await tab.getByRole('button', { name: '展开系统详情' }).click()
  await expect(tab.locator('.rp-system-details')).toContainText('运行')
  await expect(tab.locator('.rp-system-details')).not.toContainText('系统运行')
  await expect(tab.locator('.rp-system-details')).toContainText('CPU')
  await expect(tab.locator('.rp-system-details')).toContainText('内存')
  await expect(tab.locator('.rp-system-details')).toContainText(/内置存储|硬盘/)
  await expect(tab.locator('.rp-system-details')).toContainText('GPU')
  const systemDetails = tab.locator('.rp-system-details')
  await expect(systemDetails).toContainText(/显示器数量/)
  await expect(systemDetails).toContainText(/显示器1|不可用/)
  await expect(tab.getByText('主屏', { exact: true })).toHaveCount(0)
  await expect(tab.getByText('副屏', { exact: true })).toHaveCount(0)
  await expect(tab.locator('.rp-system-details')).not.toContainText('估算')
  const detailRows = tab.locator('.rp-system-details .rp-system-detail-row')
  await expect(detailRows.nth(0).locator(':scope > span').first()).toHaveText('系统')
  await expect(detailRows.nth(1).locator(':scope > span').first()).toHaveText('运行')
  await expect(detailRows.nth(2).locator(':scope > span').first()).toHaveText('CPU')
  await expect(detailRows.nth(3).locator(':scope > span').first()).toHaveText('内存')
  await expect(tab.locator('.rp-runtime-detail-value strong')).toBeVisible()
  await expect(detailRows.nth(0).locator('strong')).toContainText('·')
  const runtimeDetailsToggle = tab.getByRole('button', { name: '收拢系统详情' })
  await expect(runtimeDetailsToggle).toBeVisible()
  await runtimeDetailsToggle.click()
  await expect(tab.getByRole('button', { name: '展开系统详情' })).toBeVisible()
  await expect(tab.locator('.rp-system-details')).toHaveCount(0)
  await tab.getByRole('button', { name: '展开系统详情' }).click()
  await expect(tab.locator('.rp-system-details')).toBeVisible()
  await expect(tab.getByText('网速状态', { exact: true })).toHaveCount(0)
  await expect(tab.getByRole('img', { name: /^资源状态:/ })).toHaveCount(1)
  await expect(tab.getByRole('img', { name: /^GPU:/ })).toHaveCount(0)
  await expect(tab.locator('.rp-gauge[title]')).toHaveCount(0)
  await expect(tab.getByRole('region', { name: 'Workspace 任务摘要' })).toHaveCount(0)
  await expect(tab.getByText('模拟任务摘要', { exact: true })).toHaveCount(0)
  await expect(tab.locator('.rp-capability-note')).toHaveCount(0)
  expect(extension.errors).toEqual([])
  expect(extension.remoteRequests).toEqual([])
})
