import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
const mock = vi.hoisted(() => ({ acquire: vi.fn(), check: vi.fn(), request: vi.fn(), rangeOpen: vi.fn(), parse: vi.fn(), permission: vi.fn(), contains: vi.fn(), select: vi.fn(), export: vi.fn() }))
vi.mock('../../browser/real/fileManagerIO', () => ({ requireExtensionFiles() {}, selectOneFile: mock.select, offerFileExport: mock.export }))
vi.mock('unas-src/platform/extension/extensionPlatform', () => ({ extensionApi: () => ({ permissions: { request: mock.permission, contains: mock.contains } }) }))
vi.mock('unas-src/platform/webdav/client', () => ({ WebDavClient: class { constructor(readonly endpoint: string) {} request = mock.request } }))
vi.mock('unas-src/platform/webdav/rangeReader', () => ({ WebDavRangeReader: { open: mock.rangeOpen } }))
vi.mock('unas-src/platform/webdav/listing', async original => ({ ...await original<typeof import('../listing')>(), parseDavListing: mock.parse }))
vi.mock('../connections', () => ({ acquireWebDavConnection: mock.acquire, checkWebDavConnection: mock.check }))
import { createDavFilesPort } from './davFiles'

const input = { endpoint: 'https://dav.example/files/', username: 'user', appPassword: 'secret', consent: true }
const listing = { path: '', entries: [{ path: 'proof.txt', name: 'proof.txt', type: 'file', size: 5, etag: '"version-1"' }, { path: 'folder/', name: 'folder', type: 'directory', size: 0 }], truncated: false }
beforeEach(() => {
  vi.resetAllMocks()
  mock.permission.mockResolvedValue(true); mock.contains.mockResolvedValue(true)
  mock.request.mockResolvedValue({ status: 207, data: new TextEncoder().encode('<xml/>') })
  mock.parse.mockReturnValue(listing)
  mock.acquire.mockResolvedValue({ ...input, id: 'shared', revision: 'v1', vaultEndpoint: input.endpoint + '.unas-vault/' })
  mock.check.mockResolvedValue(undefined)
  vi.stubGlobal('navigator', { locks: { request: async (_name: string, _options: unknown, action: (lock: object) => Promise<unknown>) => await action({}) } })
})
afterEach(() => vi.unstubAllGlobals())

describe('WebDAV file service', () => {
  it('requires independent consent and permission before sending any request', async () => {
    const port = createDavFilesPort()
    await expect(port.connect({ ...input, consent: false })).rejects.toThrow('确认')
    expect(mock.permission).not.toHaveBeenCalled()
    mock.permission.mockResolvedValue(false)
    await expect(port.connect(input)).rejects.toThrow('未授予')
    expect(mock.request).not.toHaveBeenCalled()
    expect(mock.permission).toHaveBeenCalledWith({ origins: ['https://dav.example/*'] })
  })
  it('owns the connection attempt while the permission dialog is pending', async () => {
    let release!: (granted: boolean) => void
    mock.permission.mockReturnValue(new Promise<boolean>(resolve => { release = resolve }))
    const port = createDavFilesPort()
    const connection = port.connect(input)
    await expect(port.connect(input)).rejects.toThrow('正在执行')
    port.disconnect(); release(true)
    await expect(connection).rejects.toThrow('取消')
    expect(mock.request).not.toHaveBeenCalled()
  })
  it('never overwrites a named upload and rejects unexpected success statuses', async () => {
    const port = createDavFilesPort(); await port.connect(input)
    mock.select.mockResolvedValue(new File(['hello'], 'proof.txt'))
    mock.request.mockResolvedValue({ status: 201 })
    await port.upload('')
    expect(mock.request).toHaveBeenLastCalledWith('PUT', 'proof.txt', expect.objectContaining({ headers: { 'If-None-Match': '*', 'Content-Type': 'application/octet-stream' } }))
    mock.request.mockResolvedValue({ status: 204 })
    await expect(port.upload('')).rejects.toThrow('HTTP 204')
  })
  it('uses conditional deletion and refuses directories or weak ETags', async () => {
    const port = createDavFilesPort(); await port.connect(input)
    mock.request.mockResolvedValue({ status: 204 })
    await port.deleteFile('proof.txt')
    expect(mock.request).toHaveBeenLastCalledWith('DELETE', 'proof.txt', expect.objectContaining({ headers: { 'If-Match': '"version-1"' } }))
    await expect(port.deleteFile('folder/')).rejects.toThrow('目录不允许')
    mock.parse.mockReturnValue({ ...listing, entries: [{ ...listing.entries[0], etag: 'W/"weak"' }] })
    mock.request.mockResolvedValue({ status: 207, data: new Uint8Array() }); await port.list('')
    await expect(port.deleteFile('proof.txt')).rejects.toThrow('强 ETag')
  })
  it('stops after permission revocation and rejects unlisted resources', async () => {
    const port = createDavFilesPort(); await port.connect(input)
    mock.contains.mockResolvedValue(false); mock.request.mockClear()
    await expect(port.list('')).rejects.toThrow('已撤销')
    await expect(port.list('outside/')).rejects.toThrow('已读取')
    await expect(port.download('secret.txt')).rejects.toThrow('当前列表')
    expect(mock.request).not.toHaveBeenCalled()
  })
  it('reports uncertain remote writes without retrying after a network error', async () => {
    const port = createDavFilesPort(); await port.connect(input)
    mock.request.mockClear().mockRejectedValue(new Error('网络请求失败'))
    await expect(port.createDirectory('', 'new')).rejects.toThrow('结果尚未确认')
    expect(mock.request).toHaveBeenCalledOnce()
  })
  it('opens an opaque file reference and saves text only with the listed strong ETag', async () => {
    const port = createDavFilesPort(); await port.connect(input)
    const ref = await port.createFileRef('proof.txt')
    mock.request.mockResolvedValueOnce({ status: 200, headers: new Headers({ ETag: '"version-2"' }), data: new Uint8Array() })
    await port.saveText(ref, '# edited')
    expect(mock.request).toHaveBeenLastCalledWith('PUT', 'proof.txt', expect.objectContaining({
      headers: { 'If-Match': '"version-1"', 'Content-Type': 'text/plain; charset=utf-8' },
      body: new TextEncoder().encode('# edited'),
    }))
    mock.request.mockResolvedValueOnce({ status: 412, headers: new Headers(), data: new Uint8Array() })
    await expect(port.saveText(ref, '# stale edit')).rejects.toThrow('版本冲突')
    expect(mock.request).toHaveBeenCalledTimes(3)
  })
  it('streams only bounded ranges through the shared authenticated WebDAV reader', async () => {
    const rangeRead = vi.fn(async (start: number, length: number) => new TextEncoder().encode('abcde').slice(start, start + length))
    const rangeClose = vi.fn()
    mock.rangeOpen.mockResolvedValue({ metadata: { size: 5, etag: '"version-1"' }, read: rangeRead, close: rangeClose })
    const port = createDavFilesPort(); await port.connect(input)
    const ref = await port.createFileRef('proof.txt')
    const lease = await port.openRead(ref, { offset: 1, length: 3 })
    expect(lease.length).toBe(3)
    expect(await new Response(lease.stream).text()).toBe('bcd')
    expect(rangeRead).toHaveBeenCalledWith(1, 3, undefined)
    expect(rangeClose).toHaveBeenCalledOnce()
  })
  it('rejects a cross-page lock before writing', async () => {
    const port = createDavFilesPort(); await port.connect(input)
    vi.stubGlobal('navigator', { locks: { request: async (_name: string, _options: unknown, action: (lock: null) => Promise<unknown>) => await action(null) } })
    mock.request.mockClear()
    await expect(port.deleteFile('proof.txt')).rejects.toThrow('另一个页面')
    expect(mock.request).not.toHaveBeenCalled()
  })
})

describe('shared file connections', () => {
  it('acquires authentication by ID and refuses further requests after the configuration changes', async () => {
    const port = createDavFilesPort()
    await port.connect({ endpoint: input.endpoint, connectionId: 'shared', consent: true })
    expect(mock.acquire).toHaveBeenCalledWith('shared')
    mock.check.mockRejectedValue(new Error('配置已更新'))
    mock.request.mockClear()
    await expect(port.deleteFile('proof.txt')).rejects.toThrow('已更新')
    expect(mock.request).not.toHaveBeenCalled()
  })
  it('hides the system Vault folder and rejects creating a reserved name', async () => {
    mock.parse.mockReturnValue({ ...listing, entries: [...listing.entries, { path: '.unas-vault/', name: '.unas-vault', type: 'directory', size: 0 }] })
    const port = createDavFilesPort()
    const connected = await port.connect({ endpoint: input.endpoint, connectionId: 'shared', consent: true })
    expect(connected.listing.entries.map(entry => entry.name)).not.toContain('.unas-vault')
    mock.request.mockClear()
    await expect(port.createDirectory('', '.unas-vault')).rejects.toThrow('系统管理')
    expect(mock.request).not.toHaveBeenCalled()
  })
  it('protects the old objects folder for migrated Vault roots', async () => {
    mock.acquire.mockResolvedValue({ ...input, id: 'shared', revision: 'v1', vaultEndpoint: input.endpoint })
    mock.parse.mockReturnValue({ ...listing, entries: [...listing.entries, { path: 'objects/', name: 'objects', type: 'directory', size: 0 }] })
    const port = createDavFilesPort()
    const connected = await port.connect({ endpoint: input.endpoint, connectionId: 'shared', consent: true })
    expect(connected.listing.entries.map(entry => entry.name)).not.toContain('objects')
    await expect(port.list('objects/')).rejects.toThrow('系统管理')
  })
  it('cannot complete a cancelled acquisition or use a changed endpoint', async () => {
    let resolve!: (value: unknown) => void
    mock.acquire.mockImplementationOnce(() => new Promise(done => { resolve = done }))
    const port = createDavFilesPort()
    const pending = port.connect({ endpoint: input.endpoint, connectionId: 'shared', consent: true })
    await vi.waitFor(() => expect(resolve).toBeDefined())
    port.disconnect(); resolve({ ...input, id: 'shared', revision: 'v1' })
    await expect(pending).rejects.toThrow('取消')
    expect(mock.request).not.toHaveBeenCalled()
    mock.acquire.mockResolvedValueOnce({ ...input, endpoint: 'https://other.example/' })
    await expect(port.connect({ endpoint: input.endpoint, connectionId: 'shared', consent: true })).rejects.toThrow('已更新')
  })
})
